{% set name = "cogwheel-pe" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cogwheel_pe-{{ version }}.tar.gz
  sha256: 1c51588b82833c03d0ee19b6719e5f2a50f44878c431893f23af22a47faaf3e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - python-lalsimulation
    - python >=3.9
    - ipykernel
    - ipympl
    - ipywidgets
    - matplotlib-base
    - notebook
    - numba
    - pandas
    - pyarrow
    - scipy
    - setuptools-scm
    - gwpy
    - dynesty
    - nautilus-sampler
    - pymultinest
    - zeus-mcmc

test:
  imports:
    - cogwheel
    - cogwheel.sampling
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jroulet/cogwheel
  summary: Parameter estimation of gravitational wave sources
  dev_url: https://github.com/jroulet/cogwheel
  license: GPL-3.0-or-later
  license_file: license

extra:
  recipe-maintainers:
    - jroulet
